listener {
    timeout = 300
    on-timeout = ~/.config/qylock/quickshell-lockscreen/lock.sh
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
