cursor #e5e2e3
cursor_text_color #c8c6c7

foreground            #e5e2e3
# background            #141414
selection_foreground  #2e3038
selection_background  #c5c6d0
url_color             #c3c6d6

# black
# color8   #585252
# color0   #4c4c4c

# red
color1   #b8545b
color9   #b15b5f

# green
color2   #c3c6d6
color10  #c3c6d6

# yellowwa
color3   #b1aa63
color11  #beb769

# blue
/* color4  #776dafff */
color4  #c3c6d6
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
