background #1a1b26
foreground #c8d3f5
url_color #82aaff
cursor #c8d3f5
selection_background #364a82
selection_foreground #c8d3f5
color0  #1a1b26
color1  #f7768e
color2  #c3e88d
color3  #ffc777
color4  #82aaff
color5  #c099ff
color6  #86e1fc
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #c3e88d
color11 #ffc777
color12 #82aaff
color13 #c099ff
color14 #86e1fc
color15 #c8d3f5
active_tab_background   #82aaff
active_tab_foreground   #1a1b26
inactive_tab_background #1a1b26
inactive_tab_foreground #565f89
