$accent = rgba(d65d0eee)
$accent_solid = rgba(d65d0eff)
$inactive = rgba(a89984aa)
$group_inactive = rgba(d5c4a1dd)
$group_text = rgba(3c3836ff)

general {
    col.active_border = $accent_solid
    col.inactive_border = $inactive
}

misc {
    background_color = rgba(fbf1c7ff)
}

plugin {
    hyprbars {
        bar_text_font = Maple Mono NF, Geist, Inter, Roboto, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(fbf1c7ff)
        col.text = rgba(3c3836ff)

        hyprbars-button = rgb(3c3836), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(3c3836), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(3c3836), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}
