$text_color = rgba(3c3836ff)
$subtext_color = rgba(665c54ff)
$overlay_color = rgba(928374ff)
$accent_color = rgba(d65d0eff)
$urgent_color = rgba(cc241dff)
$entry_background_color = rgba(fbf1c7ee)
$entry_border_color = rgba(d65d0eff)
$entry_color = rgba(3c3836ff)

$font_family = Maple Mono NF
$font_family_clock = Maple Mono NF Bold

$background_image = /home/anonymous/.dotfiles/themes/themes/cozy-white/wallpaper.jpg
