# tmux palette · COZY-WHITE (Gruvbox Light)
set -g @col_bg "#ebdbb2"
set -g @col_fg "#3c3836"
set -g @col_sep "#928374"
set -g @col_git "#79740e"
set -g @col_tab_off "#a89984"
set -g @col_tab_on "#d65d0e"

set -g status-style "bg=default,fg=#3c3836"
setw -g pane-active-border-style "fg=#d65d0e"
setw -g pane-border-style "fg=#d5c4a1"
