# tmux palette · MOCHA (dark default)
set -g @col_bg "#303030"
set -g @col_fg "#c6c6c6"
set -g @col_sep "#808080"
set -g @col_git "#a6e3a1"
set -g @col_tab_off "#6c7086"
set -g @col_tab_on "#79dac8"

set -g status-style "bg=default,fg=#c6c6c6"
setw -g pane-active-border-style "fg=#d183e8"
setw -g pane-border-style "fg=#303030"
