command = "xdg-open %VALUE%"

[[entries]]
default = true
name = "Brave Search"
url = "https://search.brave.com/search?q=%TERM%"

[[entries]]
name = "YouTube"
prefix = "yt "
url = "https://www.youtube.com/results?search_query=%TERM%"

[[entries]]
name = "GitHub"
prefix = "gh "
url = "https://github.com/search?q=%TERM%"
