[ids]
*

[main]
# We use 'meta' instead of 'super' just to be safe
capslock = overload(vim_layer, esc)

[vim_layer]

# For navigation
h = left
j = down
k = up
l = right

# GNOME shortcuts
n = M-n
m = M-m

# Word forward
w = C-right
# Word backward
b = C-left
# Start of line
0 = home
# End of line
4 = end

# Yank (Copy)
y = C-c
# Put (Paste)
p = C-v
# Visual (Select all)
v = C-a
# Undo
u = C-z
# Delete
x = delete

# Delete motions
d = oneshot(delete_layer)

# Tap Space to enter one-shot numpad mode
space = oneshot(numpad_super)

[numpad_super]
# Top row: 7 8 9
u = M-7
i = M-8
o = M-9
# Middle row: 4 5 6
j = M-4
k = M-5
l = M-6
# Bottom row: 1 2 3
m = M-1
comma = M-2
dot = M-3

[delete_layer]
# Delete the word under the cursor
w = macro(C-left C-S-right delete)
# Delete the right word
l = C-delete
# Delete the left word
h = C-backspace
# Delete the whole line
4 = macro(home S-end backspace)
