shell = "zsh"

[plugins]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

# fast-syntax-highlighting
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.extract]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/extract"

[templates]
