background #1b1d2e
foreground #edf2f4
url_color #52b788
cursor #edf2f4
selection_background #3a3d5c
selection_foreground #edf2f4
color0  #1b1d2e
color1  #ef233c
color2  #52b788
color3  #e9c46a
color4  #8d99ae
color5  #b5838d
color6  #76c8ae
color7  #edf2f4
color8  #4a4e69
color9  #ef233c
color10 #52b788
color11 #e9c46a
color12 #8d99ae
color13 #b5838d
color14 #76c8ae
color15 #edf2f4
active_tab_background   #52b788
active_tab_foreground   #1b1d2e
inactive_tab_background #1b1d2e
inactive_tab_foreground #4a4e69
