theme = "cozy"
close_when_open = true
click_to_close = true
single_click_activation = true
force_keyboard_focus = true
keybind_symbols = true

[shell]
layer = "overlay"
exclusive_zone = -1
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "search", list = "nothing here" }

[providers]
default = ["desktopapplications"]
empty = ["desktopapplications"]
max_results = 25

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "."
provider = "unicode"

[[providers.prefixes]]
prefix = "~"
provider = "clipboard"

[[providers.prefixes]]
prefix = "/"
provider = "menus:commands"

[providers.clipboard]
time_format = "relative"
