$DESKTOP_SHELL = ags-sys24

general {
    border_size = 2
    col.active_border = rgba(c89dd4ff)
    col.inactive_border = rgba(45475a88)
    gaps_in = 4
    gaps_out = 8
}

decoration {
    rounding = 0
    blur {
        enabled = true
        size = 4
        passes = 2
        brightness = 0.9
        noise = 0.02
        contrast = 0.95
        vibrancy = 0.1
    }
    shadow {
        enabled = false
    }
    dim_inactive = true
    dim_strength = 0.1
}

animations {
    enabled = false
}

group {
    col.border_active = rgba(c89dd4ff)
    col.border_inactive = rgba(6c7086aa)
    groupbar {
        enabled = true
        font_family = Maple Mono NF
        font_size = 11
        height = 22
        indicator_height = 2
        gaps_in = 0
        gaps_out = 0
        col.active = rgba(181825ff)
        col.inactive = rgba(11111bff)
        text_color = rgba(cdd6f4ff)
        rounding = 0
        gradient_rounding = 0
    }
}

misc {
    background_color = 0x11111b
}

plugin {
    hyprbars {
        bar_color = rgba(181825ff)
        bar_text_color = rgba(c89dd4ff)
        bar_text_font = Maple Mono NF
        bar_height = 18
        bar_padding = 14
        bar_text_size = 9
        bar_buttons_alignment = none
        bar_title_enabled = true
        bar_part_of_window = true
        bar_precedence_over_border = true
        bar_text_align = left
    }
}
