[[quote]]
japanese = "あんた方は俺の敵じゃない。俺に敵なんかいない。"
translation = "You are not my enemy. I have no enemies."
romaji = "Anta kata wa ore no teki janai. Ore ni teki nanka inai."
source = "Thorfinn Karlsefni - Vinland Saga"

