general {
    col.active_border = rgba(b4befeff)
    col.inactive_border = rgba(6c7086aa)
}

misc {
    background_color = rgba(1e1e2eff)
}

plugin {
    hyprbars {
        bar_text_font = Maple Mono NF, Geist, Inter, Roboto, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(1e1e2eff)
        col.text = rgba(cdd6f4ff)

        hyprbars-button = rgb(cdd6f4), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(cdd6f4), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(cdd6f4), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}
