# UI-specific keybinds — Quickshell mode
$mod = SUPER
bind = $mod, SPACE, global, quickshell:searchToggle
bind = $mod, A, global, quickshell:sidebarLeftToggle
bind = $mod, PERIOD, global, quickshell:sidebarRightToggle
bind = $mod, O, global, quickshell:overlayToggle
bind = $mod, SLASH, global, quickshell:cheatsheetToggle
bind = $mod CTRL, M, global, quickshell:mediaControlsToggle
bind = $mod SHIFT, V, global, quickshell:overviewClipboardToggle
bind = $mod SHIFT, W, global, quickshell:wallpaperSelectorToggle
bind = $mod SHIFT, S, global, quickshell:regionScreenshot
bindd = Ctrl+Alt, Delete, Toggle session menu, global, quickshell:sessionToggle
bind = Ctrl+$mod, R, exec, killall qs quickshell; qs -c ii &
bind = $mod, F4, exec, ~/.dotfiles/scripts/ags-run.sh
bind = $mod, F5, exec, ~/.dotfiles/scripts/ags-reload.sh
